name: Release CI

on: [push]

jobs:
  releaseJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Use different mod metadata
      run: |
        rm mod.hjson
        printf 'name: "ion"\ndisplayName: "Ion"\nauthor: "TeamNeiaron"\nsubtitle: "BE Build ${{ github.run_number }}"\nversion: ${{ github.run_number }}\nminGameVersion: 136\nmain: "ion.Ion"' >> mod.hjson
    - name: Build mod jar
      run: ./gradlew deploy -Duse-k2
    - name: Upload built jar file
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GTOKEN }}
        repo_name: TeamNeiaron/IonBuilds
        file: build/libs/Ion.jar
        tag: ${{ github.run_number }}
